apiVersion: v1
kind: Service
metadata:
  name: ejercicioservice-srv
spec:
  type: NodePort
  selector:
    app: ejercicioservice
  ports:
    - name: ejercicioservice
      protocol: TCP
      port: 8080
      targetPort: 8080